### ISSUE TITLE
Is there a way to not force aspect ratio being maintained?

### ISSUE THREAD

**Issue by spsiddarthan** [danschumann/limby-resize#8]
@danschumann, Great work with the library, so congrats on that! 

 I am trying to resize a gif using imagemagick, but the aspect ratio is always maintained. Is there a way we can override this?

**Comment by danschumann** [comment]
You know, in retrospect, I think the main value of this library is the resize algorithm itself, but that doesn't even use imagemagick.  If I were you, using imagemagick, I would just use imagemagick directly.  Not sure why I even included that functionality.

https://github.com/rsms/node-imagemagick

THe following is untested but would probably work
```
var im = require('imagemagick');
im.convert(['kittens.jpg', '-resize', '25x120', 'kittens-small.jpg'], 
function(err, stdout){
  if (err) throw err;
  console.log('stdout:', stdout);
});
```

Eventually I plan to update this library to add webgl support where available ( because resizing through that is much faster ), and I'll probably end up removing imagemagick support, because I don't really add any value if imagemagick is available.

**Comment by danschumann** [comment]
also see this post: http://www.imagemagick.org/discourse-server/viewtopic.php?t=29097

I think you have to do the width like `'25x120!'` with an exclamation point to break the aspect ratio

You could potentially keep using limby-resize w/ image magick.. Potentially adding an exclamation to your height would work `height: 100+'!'`
